name: Update Theme Date
on:
  push:
    paths:
      - 'themes/**'

jobs:
  submitPR:
    permissions: write-all
    name: Update theme date after update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Get changed folders
        id: get_changes
        run: |
          # Get the list of modified directories in the themes folder
          changed_dirs=$(git diff --name-only HEAD^ HEAD | grep '^themes/' | awk -F/ '{print $2}' | sort -u)
          echo "CHANGED_DIRS=$changed_dirs" >> $GITHUB_ENV

      - name: Setup python modules
        run: |
          pip3 install requests

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update theme date
        if: env.CHANGED_DIRS != ''
        run: |
          for dir in $CHANGED_DIRS; do
            # Assuming the theme ID is the same as the folder name
            python3 scripts/update_theme_date.py "themes/$dir"
          done

      - name: Commit changes
        run: |
          git add theme.json
          git add themes/*/theme.json
          git commit -m "Update updatedAt field in theme.json after theme update"
          git push
